name: CI/CD Pipeline

on:
  push:
    branches: [main, develop, feature/cicd-setup]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run Tests
        run: pytest -s

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # 1. StratÃ©gie Orpheline (Clean Slate)
          git checkout --orphan deploy-branch
          git rm -rf --cached .
          
          # 2. SOLUTION RADICALE : On Ã©crase le README.md qui bloque
          # On gÃ©nÃ¨re un en-tÃªte valide pour dire Ã  HF "C'est un projet Docker"
          echo "---" > README.md
          echo "title: Mon API ML" >> README.md
          echo "emoji: ðŸš€" >> README.md
          echo "colorFrom: blue" >> README.md
          echo "colorTo: red" >> README.md
          echo "sdk: docker" >> README.md
          echo "app_port: 8000" >> README.md
          echo "---" >> README.md
          echo "" >> README.md
          echo "# Documentation API" >> README.md
          echo "DÃ©ploiement automatique via GitHub Actions." >> README.md
          
          # 3. Gestion LFS des binaires
          git lfs install
          git lfs track "*.joblib"
          git lfs track "*.png"
          git add .gitattributes
          
          # 4. Ajout de tout le reste
          git add .
          
          # 5. Envoi
          git commit -m "Deploy with fresh README"
          git push --force https://EthanChmt:$HF_TOKEN@huggingface.co/spaces/EthanChmt/Dev_modele_ML deploy-branch:main